apiVersion: apps/v1
kind: Deployment
metadata:
  name: crm-service
  namespace: bookstore-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crm-service
  template:
    metadata:
      labels:
        app: crm-service
    spec:
      containers:
      - name: crm-service
        image: linyul/crm-service:latest
        imagePullPolicy: Always
        env:
        - name: KAFKA_SERVERS
          valueFrom:
            configMapKeyRef:
              name: bookstore-config
              key: kafka-servers
        - name: SMTP_USER
          valueFrom:
            secretKeyRef:
              name: bookstore-secrets
              key: smtp-user
        - name: SMTP_PASS
          valueFrom:
            secretKeyRef:
              name: bookstore-secrets
              key: smtp-pass